# Generated by Django 4.1.4 on 2023-01-04 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SenderInfo',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('module_path', models.CharField(max_length=512, unique=True, verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Отправщик данных',
                'verbose_name_plural': 'Отправщики данных',
            },
        ),
        migrations.CreateModel(
            name='SendStrategyInfo',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('module_path', models.CharField(max_length=512, unique=True, verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Стратегия отправки',
                'verbose_name_plural': 'Стратегии отправки',
            },
        ),
        migrations.CreateModel(
            name='DataGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название шлюза')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('enabled', models.BooleanField(default=True, verbose_name='Активен')),
                ('send_strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_gateways', related_query_name='data_gateway', to='message_sender.sendstrategyinfo', verbose_name='Стратегия отправки')),
            ],
            options={
                'verbose_name': 'Шлюз данных',
                'verbose_name_plural': 'Шлюзы данных',
            },
        ),
        migrations.CreateModel(
            name='SenderGatewayRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
                ('enabled', models.BooleanField(default=True, verbose_name='Активен')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('data_gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_relations', related_query_name='sender_relation', to='message_sender.datagateway', verbose_name='Шлюз данных')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_relations', related_query_name='gateway_relation', to='message_sender.senderinfo', verbose_name='Отправщик данных')),
            ],
            options={
                'verbose_name': 'Связь с отправщиком',
                'verbose_name_plural': 'Связи с отправщиками',
                'ordering': ('serial_number',),
                'unique_together': {('serial_number', 'data_gateway')},
            },
        ),
    ]
