"""
Django settings for django_message_sender project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u8=v=%5^cy_h80_+9$xwz#&$crfk^!eq+!kj$%)^n63!jr^r(8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_message_sender.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_message_sender.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Настройки отправщиков сообщений.
# TODO: Сейчас важно указывать стратегии отправки в порядке, будто бы 
#   мы их "определяем". Т.е. не должно быть такого, что мы где-то 
#   используем стратегию отправки, которая определена ниже. Это важно, 
#   потому что ее еще не будет в БД.
#   Чтобы избавиться от важности порядка стратегий, можно в будущем добавить 
#   класс, который будет находить зависимости между стратегиями и список конфигураций 
#   сортировать в нужном порядке. Тогда саму конфигурацию можно будет прописывать хоть как.
MESSAGE_SENDER = {
    'INIT_FILE_NAME': 'message_sender',
    'SENDER_CONFIGS': (
        {
            'name': 'KanalservisTelegramGroupsSender_config_1',
            'description': 'Какое-то описание конфигурации',
            'sender_name': 'KanalservisTelegramGroupsSender',
            'params': {
                'bot_token': TELEGRAM_BOT_TOKEN,
                'main_group_id': TELEGRAM_GROUP_ID,
                'duty_group_id': TELEGRAM_DUTY_ID,
                'duty_start_time': '22:00:00',
                'duty_end_time': '07:00:00',
            },
        },
    ),
    'STRATEGY_CONFIGS': (
        {
            'name': 'AllSystemsSendStrategy_config_1',
            'strategy_name': 'AllSystemsSendStrategy',
            'senders': (
                {
                    'serial_number': 1,
                    'enabled': True,
                    'sender_config': 'KanalservisTelegramGroupsSender_config_1',
                },
            ),
        },
    ),
    'DATA_GATEWAYS': (
        {
            'name': 'Telegram Groups',
            'description': 'Шлюз отправки данных в телеграм-группы в зависимости от времени.',
            'strategy_config': 'AllSystemsSendStrategy_config_1',
        },
    ),
}
